### ISSUE TITLE
Custom_Lint Does not work in git pre-commit script

### ISSUE THREAD

**Issue by shambhavi-dev** [invertase/dart_custom_lint#184]
my main goal is to prevent commit using git hooks if 'flutter analyze' and 'dart run custom_lint' return issues exist in code.
So when I write below code and try to commit the code It says cannot find custom_lint file in git bash.

#!/bin/bash

# Run custom_lint
echo "Running custom_lint..."
dart run custom_lint

# Check the exit code of custom_lint
if [ $? -ne 0 ]; then
  echo "Custom linting issues found. Aborting commit."
  exit 1
fi

# Run flutter analyze
echo "Running flutter analyze..."
flutter analyze

# Check the exit code of flutter analyze
if [ $? -ne 0 ]; then
  echo "Linting issues found. Aborting commit."
  exit 1
fi

tried to nstall custom_lint globally (dart pub global activate custom_lint) and run custom_lint (without dart run), but did not work.

Got below error:
```
Running custom_lint...
.git/hooks/pre-commit: line 6: custom_lint: command not found
Custom linting issues found. Aborting commit.

git did not exit cleanly (exit code 1) (1141 ms @ 8/31/2023 4:35:25 PM)
```

if you can suggest something here as well. It would be really grateful.

**Comment by rrousselGit** [comment]
Not finding the "custom_lint" command is not custom_lint's responsibility.

That's either about the Dart SDK (such as global installation not working properly) or your environment (such as PATH not listing the location of where Dart bins are installed).
custom_lint isn't involved in the process at all here

Make sure your PATH includes `~/.pub-cache/bin`, which is typically where Dart bins are installed.

Note that if you have access to `dart`, you could also try running commands with `dart pub global run custom_lint` instead of just `custom_lint`
