### ISSUE TITLE
Improve error message when there are conflicting package versions

### ISSUE THREAD

**Issue by rrousselGit** [invertase/dart_custom_lint#89]
It's be great if the error message about conflicting dependency versions in 2+ contextroots could include:
- the package names causing the problem
- suggest to run "pub upgrade" in both packages
- suggest checking that the pubspecs correctly allow the version everywhere

**Comment by adsonpleal** [comment]
Hey Remi! 

I was having this issue on a multi-package project using `melos`. I'm wondering if there is a way to "ignore" this problem. Since my project was running fine I'm guessing that the `flutter pub get` command in the root project finds a way to solve this kind of conflict. 

But well, the issue was that the sub-packages had their own `pubspec.lock` files with older versions of lots of packages.

I couldn't find an elegant solution so I did a brute force one 😂 . I added a `delete-all-locks` command to melos to remove all .lock files, then I ran `melos bs` again and the sub-packages got the right dependencies.

```yaml
  delete-all-locks:
    run: melos exec -- "rm pubspec.lock"
    description: Delete all pubspec lock files
```

But all of this was not possible to grasp with the current error, since it only shows one conflict per run, so I ended up implementing a better error that shows the context root and the package.root for all the context roots. This is basically what you're describing in this issue.

So I opened a [PR with my changes](https://github.com/invertase/dart_custom_lint/pull/91), it might solve this issue.

**Comment by adsonpleal** [comment]
Also, there is another issues that I didn't fixed:

When the error happens the process just hangs, I'd expect the process to finish with an `exit code = 1`.

My CI was running on a github actions and it kept running for 6 hours 😬 .

**Comment by rrousselGit** [comment]
The error cannot reasonably be removed.

The context behind this error is as follows:
- custom_lint shares the analysis between all packages.
- As such, all plugins are started under a single process, sharing the dependencies of all the packages that use custom_lint.
- This error happens when 2+ packages use a conflicting dependency version.
- Since there's a single process for all plugins, if 2 plugins try to use different versions for a dependency, the process cannot be reasonably started.
- Trying to start the process anyway would be equivalent to doing a coin flip. In this scenario, plugins may randomly fail to start or crash without any clear reason


> My CI was running on a github actions and it kept running for 6 hours 😬 .

The CI currently hangs if it fails. If it doesn't fail, it doesn't hang. Chances are your CI is failing. Try running tests locally or check the logs.

**Comment by rrousselGit** [comment]
Done in abd851a6c69c519b9411345ad2601072ac05a026

**Comment by maxlapides** [comment]
@rrousselGit I'm experiencing a related issue. My project is a Flutter app, but I recently added a little proxy server under a directory in the root of the project. This proxy server isn't part of the app, it's just a tool for local development. As such, I don't even need `custom_lint` to analyze the `proxy_server` directory. Is there any way that we can have `custom_lint` ignore it? For now, I am simply running this in CI:

```
rm proxy_server/pubspec.*
flutter pub run custom_lint
```

Additionally, as mentioned above, there is an issue where this error will not end the process. It will hang indefinitely, so unless you have a timeout set on CI, it will keep running forever.

**Comment by maxlapides** [comment]
Okay, never mind! Looks like the latest version of custom_lint resolves the issue :)
